<h1>ПАРАГРАФ 9<h1>

In [4]:
# Блок 1: Імпорт бібліотек
import numpy as np
import pandas as pd

# Налаштування виводу Pandas для зручного читання
pd.set_option('display.precision', 4)
pd.set_option('display.float_format', '{:,.4f}'.format)

print("Бібліотеки numpy та pandas успішно імпортовано.")

Бібліотеки numpy та pandas успішно імпортовано.


In [82]:
# Блок 2: Крок 1. Формування матриці X
# Повна матриця A (перші 5 рядків, як зазначено в умові "розміром 5x20")
A = np.array([
    [4, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [2, 1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6, 2, 7, 4, 8, 2, 9, 3, 5],
    [3, 1, 3, 2, 3, 4, 3, 4, 3, 2, 3, 7, 3, 8, 7, 3, 8, 3, 9, 4],
    [4, 7, 4, 2, 4, 3, 5, 7, 8, 9, 4, 10, 11, 12, 13, 9, 10, 11, 12, 13],
    [6, 3, 5, 3, 6, 4, 6, 9, 4, 6, 10, 9, 8, 9, 8, 10, 11, 17, 18, 19]
])

# Номери стовпчиків для Варіанту 4 (з таблиці на стор. 48)
# Номери: 4, 7, 9, 17
# Індекси (віднімаємо 1): 3, 6, 8, 16
var_columns_indices = [3, 6, 8, 16]

# Формуємо матрицю X (5 ознак x 4 об'єкти)
X = A[:, var_columns_indices]

print("--- Крок 1: Сформована матриця X (Варіант 4) ---")
print(X)

--- Крок 1: Сформована матриця X (Варіант 4) ---
[[ 4  7  9 17]
 [ 2  2  2  2]
 [ 2  3  3  8]
 [ 2  5  8 10]
 [ 3  6  4 11]]


In [83]:
# Блок 3: Крок 2. Видалення елемента x_43
# Завдання: "Видаляємо з матриці X елемент x_43"
# Це 4-й рядок, 3-й стовпчик (індекси 3, 2)
row_idx, col_idx = 3, 2

# Зберігаємо оригінальне значення для майбутньої оцінки
original_value = X[row_idx, col_idx]

# Створюємо копію матриці з пропуском (NaN)
X_nan = X.astype(float) # Конвертуємо в float для підтримки NaN
X_nan[row_idx, col_idx] = np.nan

print(f"--- Крок 2: Видалення елемента x_43 ---")
print(f"Видалений елемент x_43 (індекс [3, 2]): {original_value}")
print("\nМатриця X з пропуском (NaN):")
print(X_nan)

--- Крок 2: Видалення елемента x_43 ---
Видалений елемент x_43 (індекс [3, 2]): 8

Матриця X з пропуском (NaN):
[[ 4.  7.  9. 17.]
 [ 2.  2.  2.  2.]
 [ 2.  3.  3.  8.]
 [ 2.  5. nan 10.]
 [ 3.  6.  4. 11.]]


In [84]:
# Блок 4: Крок 3. Відновлення елемента (метод середнього по рядку)
# Згідно з Прикладом 19 (стор. 44), відновлюємо значення
# як середнє арифметичне інших елементів у тому ж рядку (ознака).
# Рахуємо середнє 4-го рядка (індекс 3), ігноруючи NaN
restored_value = np.nanmean(X_nan[row_idx, :])

# Створюємо відновлену матрицю
X_restored = X_nan.copy()
X_restored[row_idx, col_idx] = restored_value

print(f"--- Крок 3: Відновлення елемента x_43 ---")
print(f"Розраховане відновлене значення (x_43*): {restored_value:.4f}")
print("\nВідновлена матриця X (X_restored):")
print(X_restored)

--- Крок 3: Відновлення елемента x_43 ---
Розраховане відновлене значення (x_43*): 5.6667

Відновлена матриця X (X_restored):
[[ 4.          7.          9.         17.        ]
 [ 2.          2.          2.          2.        ]
 [ 2.          3.          3.          8.        ]
 [ 2.          5.          5.66666667 10.        ]
 [ 3.          6.          4.         11.        ]]


In [85]:
# Блок 5: Крок 4. Побудова дисперсійно-коваріаційної матриці (S_X)
# Використовуємо відновлену матрицю X_restored
# Формула з Прикладу 19 (стор. 44): S_X = (1 / (n-1)) * X_c * X_c^T
# n - кількість об'єктів (стовпчиків)
n = X_restored.shape[1] # n = 4

# 1. Рахуємо середні по рядках (ознаках)
row_means = X_restored.mean(axis=1, keepdims=True)
print(f"Середні по рядках (ознаках):\n{row_means}\n")

# 2. Центруємо матрицю X_c = X_restored - row_means
X_c = X_restored - row_means
print(f"Центрована матриця X_c:\n{X_c}\n")

# 3. Рахуємо коваріаційну матрицю S_X
S_X = (1 / (n - 1)) * (X_c @ X_c.T)

print(f"--- Крок 4: Дисперсійно-коваріаційна матриця S_X (на основі X_restored) ---")
print(S_X)
print(f"\nПримітка: Це 'початкова' оцінка, яка буде уточнена в наступних кроках.")

Середні по рядках (ознаках):
[[9.25      ]
 [2.        ]
 [4.        ]
 [5.66666667]
 [6.        ]]

Центрована матриця X_c:
[[-5.25       -2.25       -0.25        7.75      ]
 [ 0.          0.          0.          0.        ]
 [-2.         -1.         -1.          4.        ]
 [-3.66666667 -0.66666667  0.          4.33333333]
 [-3.          0.         -2.          5.        ]]

--- Крок 4: Дисперсійно-коваріаційна матриця S_X (на основі X_restored) ---
[[30.91666667  0.         14.66666667 18.11111111 18.33333333]
 [ 0.          0.          0.          0.          0.        ]
 [14.66666667  0.          7.33333333  8.44444444  9.33333333]
 [18.11111111  0.          8.44444444 10.88888889 10.88888889]
 [18.33333333  0.          9.33333333 10.88888889 12.66666667]]

Примітка: Це 'початкова' оцінка, яка буде уточнена в наступних кроках.


In [86]:
# Блок 6: Крок 5 та 6. Уточнення дисперсій та коваріацій (Ручний розрахунок)
#
# Ми реалізуємо метод попарного виключення (pairwise deletion).
# Формула коваріації s_ij розраховується на основі
# тільки тих об'єктів (стовпчиків), де і i-та, і j-та ознаки
# одночасно НЕ є пропущеними (NaN).

print("--- Крок 5 та 6: Уточнення S_X (метод попарного виключення) ---")

# Кількість ознак (рядків)
p = X_nan.shape[0] # p = 5

# Створюємо порожню матрицю 5x5 для результатів
S_refined_manual = np.zeros((p, p))

# Ітеруємо по кожній парі ознак (i, j)
for i in range(p):
    for j in range(p):

        # 1. Знаходимо "спільні" дані:
        #    Беремо i-тий та j-тий рядки
        data_i = X_nan[i, :]
        data_j = X_nan[j, :]

        #    Знаходимо індекси стовпчиків, де ОБИДВА значення не є NaN
        valid_mask = ~np.isnan(data_i) & ~np.isnan(data_j)

        #    Отримуємо чисті дані для розрахунку
        valid_i = data_i[valid_mask]
        valid_j = data_j[valid_mask]

        #    Кількість спільних повних спостережень
        n_ij = len(valid_i)

        # 2. Розраховуємо коваріацію (або дисперсію, якщо i == j)
        if n_ij < 2:
            # Недостатньо даних для розрахунку
            S_refined_manual[i, j] = np.nan
        else:
            # Формула коваріації: sum((xi - mean(x)) * (yi - mean(y))) / (n - 1)
            mean_i = np.mean(valid_i)
            mean_j = np.mean(valid_j)

            cov_ij = np.sum((valid_i - mean_i) * (valid_j - mean_j)) / (n_ij - 1)

            S_refined_manual[i, j] = cov_ij

print("Уточнена дисперсійно-коваріаційна матриця (S_refined_manual):")
# Використовуємо Pandas для гарного форматування результату
features = ['F1', 'F2', 'F3', 'F4', 'F5']
df_S_refined = pd.DataFrame(S_refined_manual, index=features, columns=features)
print(df_S_refined)

--- Крок 5 та 6: Уточнення S_X (метод попарного виключення) ---
Уточнена дисперсійно-коваріаційна матриця (S_refined_manual):
        F1     F2      F3      F4      F5
F1 30.9167 0.0000 14.6667 27.1667 18.3333
F2  0.0000 0.0000  0.0000  0.0000  0.0000
F3 14.6667 0.0000  7.3333 12.6667  9.3333
F4 27.1667 0.0000 12.6667 16.3333 16.3333
F5 18.3333 0.0000  9.3333 16.3333 12.6667


In [87]:
# Блок 7: Крок 7. Розрахунок незміщеної оцінки дисперсії (перевірка)
# "Розраховуємо незміщену оцінку дисперсії четвертої ознаки"
# Це перевірка значення S_refined[3, 3] (або 'F4', 'F4')
# Використовуємо лише ті дані, що були в оригіналі (без пропуску)
# Для 4-ї ознаки (індекс 3) це були [3, 5, 10]
data_f4_available = X_nan[row_idx, :][~np.isnan(X_nan[row_idx, :])]

# Рахуємо вручну за формулою (як у прикладі на стор. 45)
# n_i = 3
n_i = len(data_f4_available)
# mean_i = (3 + 5 + 10) / 3 = 6
mean_i = data_f4_available.mean()
# var_44 = ((3-6)^2 + (5-6)^2 + (10-6)^2) / (3-1)
# var_44 = (9 + 1 + 16) / 2 = 26 / 2 = 13
var_44_manual = np.sum((data_f4_available - mean_i)**2) / (n_i - 1)

print("--- Крок 7: Перевірка уточненої дисперсії s_44 ---")
print(f"Дані для 4-ї ознаки (без пропуску): {data_f4_available}")
print(f"Розрахована вручну дисперсія s_44: {var_44_manual:.4f}")
print(f"Дисперсія s_44 з матриці S_refined: {df_S_refined.loc['F4', 'F4']:.4f}")
print("Значення збігаються, розрахунок 'попарним методом' коректний.")

--- Крок 7: Перевірка уточненої дисперсії s_44 ---
Дані для 4-ї ознаки (без пропуску): [ 2.  5. 10.]
Розрахована вручну дисперсія s_44: 16.3333
Дисперсія s_44 з матриці S_refined: 16.3333
Значення збігаються, розрахунок 'попарним методом' коректний.


In [88]:
# Блок 8: Крок 8. Оцінка відновленого елемента (похибка)
# Згідно з Прикладом 21 (стор. 47)
# epsilon = x_original - x_restored
epsilon = original_value - restored_value

print("--- Крок 8: Оцінка похибки відновлення ---")
print(f"Оригінальне значення x_43: {original_value}")
print(f"Відновлене значення x_43*: {restored_value:.4f}")
print(f"Абсолютна похибка (epsilon_43): {epsilon:.4f}")

--- Крок 8: Оцінка похибки відновлення ---
Оригінальне значення x_43: 8
Відновлене значення x_43*: 5.6667
Абсолютна похибка (epsilon_43): 2.3333


In [89]:
# Блок 9: Крок 9. Оцінка якості заповнення пропуску
# Оскільки у нас лише одне відновлене значення,
# розрахуємо відсоткову похибку (Percentage Error, PE)
# PE = (|epsilon| / |x_original|) * 100%

PE = (np.abs(epsilon) / np.abs(original_value)) * 100

print("--- Крок 9: Оцінка якості заповнення ---")
print(f"Відсоткова похибка (PE) для x_43: {PE:.2f}%")

# Використовуємо таблицю "Оцінка MAPE" зі стор. 46
print("\nЯкісна оцінка (за таблицею зі стор. 46):")
if PE < 10:
    print(f"({PE:.2f}% < 10) -> висока точність")
elif PE <= 20:
    print(f"(10 < {PE:.2f}% <= 20) -> добра точність")
elif PE <= 50:
    print(f"(20 < {PE:.2f}% <= 50) -> задовільна точність")
else:
    print(f"({PE:.2f}% > 50) -> незадовільна точність")

print("\n--- ЗАВДАННЯ ВИКОНАНО ---")

--- Крок 9: Оцінка якості заповнення ---
Відсоткова похибка (PE) для x_43: 29.17%

Якісна оцінка (за таблицею зі стор. 46):
(20 < 29.17% <= 50) -> задовільна точність

--- ЗАВДАННЯ ВИКОНАНО ---


<h1>ПАРАГРАФ 10<h1>

In [1]:
# Блок 1: Імпорт бібліотек
import numpy as np

print("Бібліотека numpy імпортована.")

Бібліотека numpy імпортована.


In [2]:
# Блок 2: Вхідні дані (Варіант 4)

# Дані для 4-го варіанту (з таблиці на стор. 56)
X = np.array([ 6.7, 6.6, 8.2, 6.5, 6.5, 6.6, 6.6, 6.7, 8.1, 5.3])

# Кількість спостережень
N = len(X)

# Для робастних методів нам потрібна відсортована вибірка
X_sorted = np.sort(X)

print(f"--- Вхідні дані (Варіант 4) ---")
print(f"Вибірка (N={N}): {X}")
print(f"Відсортована вибірка: {X_sorted}")

--- Вхідні дані (Варіант 4) ---
Вибірка (N=10): [6.7 6.6 8.2 6.5 6.5 6.6 6.6 6.7 8.1 5.3]
Відсортована вибірка: [5.3 6.5 6.5 6.6 6.6 6.6 6.7 6.7 8.1 8.2]


In [3]:
# Блок 3: Визначення параметрів (на основі Прикладу 22)

# У Прикладі 22 (стор. 51-52) для N=10 розрахунки T(a) і W(a)
# збігаються з відповідями (2.217 і 2.23) лише при alpha = 0.2.
# (Хоча в тексті згадується alpha=0.3, розрахунок показує інше).
# Ми будемо дотримуватись логіки ПРИКЛАДУ.
alpha = 0.2

# Кількість елементів, що відсікаються/замінюються
n_a = int(np.floor(alpha * N))

print(f"--- Параметри розрахунку ---")
print(f"alpha (α) = {alpha} (на основі аналізу Прикладу 22)")
print(f"Кількість відсічених елементів (n_a) = floor({alpha} * {N}) = {n_a}")

--- Параметри розрахунку ---
alpha (α) = 0.2 (на основі аналізу Прикладу 22)
Кількість відсічених елементів (n_a) = floor(0.2 * 10) = 2


In [4]:
# Блок 4: 1. Середнє за Пуанкаре (Усічене середнє)

# Формула T(a) (стор. 51)
# Ми відсікаємо n_a=2 найменших і n_a=2 найбільших значень
# і знаходимо середнє решти (N - 2*n_a) = 6 елементів.

# Дані для розрахунку (вибірка без 2-х крайніх з кожного боку)
trimmed_data = X_sorted[n_a : N - n_a]

# Розрахунок середнього
mean_poincare = np.mean(trimmed_data)

print(f"--- 1. Середнє за Пуанкаре (T(a)) ---")
print(f"Вибірка для розрахунку: {trimmed_data}")
print(f"Розрахунок: {np.sum(trimmed_data)} / {len(trimmed_data)}")
print(f"Середнє за Пуанкаре (T(a)): {mean_poincare:.4f}")

--- 1. Середнє за Пуанкаре (T(a)) ---
Вибірка для розрахунку: [6.5 6.6 6.6 6.6 6.7 6.7]
Розрахунок: 39.7 / 6
Середнє за Пуанкаре (T(a)): 6.6167


In [5]:
# Блок 5: 2. Середнє за Вінзором (Вінзоризоване середнє)

# Формула W(a) (стор. 51)
# Ми замінюємо n_a=2 найменших значень на (n_a + 1)-те значення
# і n_a=2 найбільших значень на (N - n_a)-те значення.

# Значення для заміни
# (n_a)-й індекс (3-й елемент)
low_replace_val = X_sorted[n_a]
# (N - n_a - 1)-й індекс (8-й елемент)
high_replace_val = X_sorted[N - n_a - 1]

print(f"--- 2. Середнє за Вінзором (W(a)) ---")
print(f"Замінюємо {n_a} найменших на: {low_replace_val}")
print(f"Замінюємо {n_a} найбільших на: {high_replace_val}")

# Створюємо нову, вінзоризовану вибірку
# 1. Беремо середню частину, яка не змінюється
middle_data = X_sorted[n_a : N - n_a]
# 2. Створюємо масиви із заміненими значеннями
low_data = np.full(n_a, low_replace_val)
high_data = np.full(n_a, high_replace_val)

# 3. Об'єднуємо все
winsorized_data = np.concatenate([low_data, middle_data, high_data])

# Рахуємо середнє від цієї нової вибірки
mean_winsor = np.mean(winsorized_data)

print(f"Вінзоризована вибірка: {winsorized_data}")
print(f"Розрахунок: {np.sum(winsorized_data)} / {N}")
print(f"Середнє за Вінзором (W(a)): {mean_winsor:.4f}")

--- 2. Середнє за Вінзором (W(a)) ---
Замінюємо 2 найменших на: 6.5
Замінюємо 2 найбільших на: 6.7
Вінзоризована вибірка: [6.5 6.5 6.5 6.6 6.6 6.6 6.7 6.7 6.7 6.7]
Розрахунок: 66.10000000000001 / 10
Середнє за Вінзором (W(a)): 6.6100


In [8]:
# Блок 6: 3. Середнє за Хубером (M-оцінка)

# Приклад 22 (стор. 152) вкрай суперечливий у розрахунках,
# тому ми реалізуємо СТАНДАРТНИЙ ітеративний алгоритм Хубера,
# але з використанням константи k з прикладу.
# k(0.3) = 0.685 (стор. 151)
k = 0.685

# 1. Початкова оцінка середнього (беремо звичайне середнє)
x_mean_hub = np.mean(X)
print(f"--- 3. Середнє за Хубером (M-оцінка) ---")
print(f"Використовуємо k = {k} (з Прикладу 22)")
print(f"Початкова оцінка (звичайне середнє): {x_mean_hub:.4f}")

# 2. Ітераційний процес
# (10 ітерацій більш ніж достатньо для збіжності)
for i in range(10):
    # a. Визначаємо межі (L і U)
    L = x_mean_hub - k
    U = x_mean_hub + k

    # b. "Вінзоризуємо" вихідні дані за цими межами
    #    (np.clip "обрізає" всі значення, що виходять за межі L і U)
    X_clipped = np.clip(X, L, U)

    # c. Розраховуємо нове середнє на основі обрізаних даних
    x_mean_new = np.mean(X_clipped)

    print(f"Ітерація {i+1}: L={L:.4f}, U={U:.4f}, Нове середнє={x_mean_new:.4f}")

    # d. Перевірка на збіжність
    if np.isclose(x_mean_hub, x_mean_new):
        print("Алгоритм зійшовся.")
        break

    # e. Оновлюємо середнє для наступної ітерації
    x_mean_hub = x_mean_new

print(f"\nСереднє за Хубером: {x_mean_hub:.4f}")

--- 3. Середнє за Хубером (M-оцінка) ---
Використовуємо k = 0.685 (з Прикладу 22)
Початкова оцінка (звичайне середнє): 6.7800
Ітерація 1: L=6.0950, U=7.4650, Нове середнє=6.7225
Ітерація 2: L=6.0375, U=7.4075, Нове середнє=6.7052
Ітерація 3: L=6.0202, U=7.3902, Нове середнє=6.7001
Ітерація 4: L=6.0151, U=7.3851, Нове середнє=6.6985
Ітерація 5: L=6.0135, U=7.3835, Нове середнє=6.6981
Ітерація 6: L=6.0131, U=7.3831, Нове середнє=6.6979
Ітерація 7: L=6.0129, U=7.3829, Нове середнє=6.6979
Алгоритм зійшовся.

Середнє за Хубером: 6.6979


In [9]:
# Блок 7: Підсумкові результати

print("--- Підсумок (Варіант 4) ---")
print(f"Середнє за Пуанкаре (T(a)): {mean_poincare:.3f}")
print(f"Середнє за Вінзором (W(a)): {mean_winsor:.3f}")
print(f"Середнє за Хубером: {x_mean_hub:.3f}")

--- Підсумок (Варіант 4) ---
Середнє за Пуанкаре (T(a)): 6.617
Середнє за Вінзором (W(a)): 6.610
Середнє за Хубером: 6.698
