<h1>ПАРАГРАФ 6<h1>

In [1]:
import numpy as np
from scipy import stats

In [2]:
# Задаємо значення i
i = 4

# Вибірка 1
# 2.6 + i; 6.7 + 2i; 4.6; 9.4 + i; 9.8; 4 + i; 6.3 + i; 7 + i; 8.7 + i; 10 + i
sample1 = np.array([
    2.6 + i,
    6.7 + 2*i,
    4.6,
    9.4 + i,
    9.8,
    4 + i,
    6.3 + i,
    7 + i,
    8.7 + i,
    10 + i
])

# Вибірка 2
# 3.7; 4.2 + i; 6.7 + i; 8.3 + i; 6.1 + i; 8.9 + i; 5 + i; 3.9 + i/2; 10 + i/2; 4.4 + i; 6 + 2i
sample2 = np.array([
    3.7,
    4.2 + i,
    6.7 + i,
    8.3 + i,
    6.1 + i,
    8.9 + i,
    5 + i,
    3.9 + i/2,
    10 + i/2,
    4.4 + i,
    6 + 2*i
])

print(f"Вибірка 1 (n1 = {len(sample1)}):")
print(sample1)
print("\n" + "="*30 + "\n")
print(f"Вибірка 2 (n2 = {len(sample2)}):")
print(sample2)

Вибірка 1 (n1 = 10):
[ 6.6 14.7  4.6 13.4  9.8  8.  10.3 11.  12.7 14. ]


Вибірка 2 (n2 = 11):
[ 3.7  8.2 10.7 12.3 10.1 12.9  9.   5.9 12.   8.4 14. ]


In [4]:
# Встановлюємо рівень значущості
alpha = 0.05

# Словник з критичними значеннями U1 і U2 з Таблиці 11.12 для alpha = 0.05
# Формат: { n: (U1, U2) }
# Ми беремо дані з колонки "alpha = 0.05"
critical_values_rs = {
    10: (2.670, 3.568),  # n = 10
    11: (2.740, 3.800)   # n = 11
    # ... додайте інші значення з таблиці за потреби
}

print("--- Перевірка на нормальність (Критерій Девіда-Хартлі-Пірсона) ---")
print(f"Рівень значущості alpha = {alpha}\n")

# --- Перевірка для Вибірки 1 ---
print("Вибірка 1:")
n1 = len(sample1)
if n1 not in critical_values_rs:
    print(f"  Помилка: Критичні значення для n={n1} відсутні у нашому словнику.")
else:
    # 1. Знаходимо критичні значення
    u1_crit, u2_crit = critical_values_rs[n1]

    # 2. Розраховуємо статистику U_CT = R / S_B
    R1 = np.max(sample1) - np.min(sample1)
    S_B1 = np.std(sample1) # np.std() за замовчуванням ділить на n (ddof=0)
    U_CT1 = R1 / S_B1

    print(f"  Розмір вибірки n1 = {n1}")
    print(f"  Розмах R = {R1:.4f}")
    print(f"  Стандартне відхилення S_B = {S_B1:.4f}")
    print(f"  Статистика U_CT = R / S_B = {U_CT1:.4f}")
    print(f"  Критичний інтервал: ({u1_crit}, {u2_crit})")

    # 3. Приймаємо рішення
    if (U_CT1 > u1_crit) and (U_CT1 < u2_crit):
        print(f"  Висновок: {u1_crit} < {U_CT1:.4f} < {u2_crit}. Гіпотеза про нормальність H0 приймається.\n")
    else:
        print(f"  Висновок: U_CT ({U_CT1:.4f}) виходить за межі ({u1_crit}, {u2_crit}). Гіпотеза H0 відхиляється.\n")

# --- Перевірка для Вибірки 2 ---
print("Вибірка 2:")
n2 = len(sample2)
if n2 not in critical_values_rs:
    print(f"  Помилка: Критичні значення для n={n2} відсутні у нашому словнику.")
else:
    # 1. Знаходимо критичні значення
    u1_crit, u2_crit = critical_values_rs[n2]

    # 2. Розраховуємо статистику U_CT = R / S_B
    R2 = np.max(sample2) - np.min(sample2)
    S_B2 = np.std(sample2) # np.std() за замовчуванням ділить на n (ddof=0)
    U_CT2 = R2 / S_B2

    print(f"  Розмір вибірки n2 = {n2}")
    print(f"  Розмах R = {R2:.4f}")
    print(f"  Стандартне відхилення S_B = {S_B2:.4f}")
    print(f"  Статистика U_CT = R / S_B = {U_CT2:.4f}")
    print(f"  Критичний інтервал: ({u1_crit}, {u2_crit})")

    # 3. Приймаємо рішення
    if (U_CT2 > u1_crit) and (U_CT2 < u2_crit):
        print(f"  Висновок: {u1_crit} < {U_CT2:.4f} < {u2_crit}. Гіпотеза про нормальність H0 приймається.\n")
    else:
        print(f"  Висновок: U_CT ({U_CT2:.4f}) виходить за межі ({u1_crit}, {u2_crit}). Гіпотеза H0 відхиляється.\n")

--- Перевірка на нормальність (Критерій Девіда-Хартлі-Пірсона) ---
Рівень значущості alpha = 0.05

Вибірка 1:
  Розмір вибірки n1 = 10
  Розмах R = 10.1000
  Стандартне відхилення S_B = 3.1653
  Статистика U_CT = R / S_B = 3.1909
  Критичний інтервал: (2.67, 3.568)
  Висновок: 2.67 < 3.1909 < 3.568. Гіпотеза про нормальність H0 приймається.

Вибірка 2:
  Розмір вибірки n2 = 11
  Розмах R = 10.3000
  Стандартне відхилення S_B = 2.9663
  Статистика U_CT = R / S_B = 3.4724
  Критичний інтервал: (2.74, 3.8)
  Висновок: 2.74 < 3.4724 < 3.8. Гіпотеза про нормальність H0 приймається.



In [6]:
print("--- 1. F-критерій (як у секції 6.1) ---")

# Обчислюємо вибіркові дисперсії (з ddof=1 для S^2, тобто ділення на n-1)
var1 = np.var(sample1, ddof=1)
var2 = np.var(sample2, ddof=1)

# Розміри вибірок
n1 = len(sample1)
n2 = len(sample2)

# Ступені свободи
df1 = n1 - 1
df2 = n2 - 1

# F-статистика - це відношення БІЛЬШОЇ дисперсії до МЕНШОЇ
if var1 > var2:
    F_stat = var1 / var2
    dfn = df1 # ступінь свободи чисельника
    dfd = df2 # ступінь свободи знаменника
else:
    F_stat = var2 / var1
    dfn = df2
    dfd = df1

# Рахуємо p-value для двостороннього тесту
p_value_f = 2 * stats.f.sf(F_stat, dfn, dfd)

print(f"  Дисперсія S1^2 = {var1:.4f} (df1 = {df1})")
print(f"  Дисперсія S2^2 = {var2:.4f} (df2 = {df2})")
print(f"  F-статистика = {F_stat:.4f}")
print(f"  p-value = {p_value_f:.4f}")

if p_value_f > alpha:
    print("  Висновок: p-value > alpha. Немає підстав відхилити H0. Дисперсії однорідні.\n")
else:
    print("  Висновок: p-value <= alpha. Відхиляємо H0. Дисперсії неоднорідні.\n")

# ====================================================================
# ОНОВЛЕНИЙ БЛОК ДЛЯ КРИТЕРІЮ БАРТЛЕТТА
# ====================================================================

print("\n--- 2. Критерій Бартлетта (детальний розрахунок за секцією 6.2) ---")

# --- 1. Визначення параметрів з секції 6.2 ---
k = 2  # k: кількість груп (сукупностей)
n1 = len(sample1)
n2 = len(sample2)
n = n1 + n2  # n: загальний об'єм усіх вибірок

# n_j - 1 (ступені свободи для кожної вибірки)
df1 = n1 - 1
df2 = n2 - 1
n_minus_k = n - k  # n - k

# S_j^2: Дисперсія оцінки (незміщена, ddof=1)
# Це S_j^2 у формулі
s1_sq = np.var(sample1, ddof=1)
s2_sq = np.var(sample2, ddof=1)

print(f"  k (кількість сукупностей): {k}")
print(f"  n1 (об'єм вибірки 1): {n1}, n1-1 = {df1}")
print(f"  n2 (об'єм вибірки 2): {n2}, n2-1 = {df2}")
print(f"  n (загальний об'єм): {n}")
print(f"  n-k (загальні ступені свободи): {n_minus_k}")
print(f"  S1^2 (дисперсія 1): {s1_sq:.4f}")
print(f"  S2^2 (дисперсія 2): {s2_sq:.4f}")

# --- 2. Розрахунок S_B^2 (об'єднана дисперсія) ---
# S_B^2 = (1 / (n-k)) * [ (n1-1)*S1^2 + (n2-1)*S2^2 ]
pooled_var_numerator = (df1 * s1_sq) + (df2 * s2_sq)
S_B_sq = pooled_var_numerator / n_minus_k

print(f"\n  S_B^2 (об'єднана дисперсія): {S_B_sq:.4f}")

# --- 3. Розрахунок C (константа) ---
# C = 1 + (1 / (3*(k-1))) * [ (1/(n1-1) + 1/(n2-1)) - 1/(n-k) ]
k_minus_1 = k - 1
sum_term = (1 / df1) + (1 / df2)
C = 1 + (1 / (3 * k_minus_1)) * (sum_term - (1 / n_minus_k))

print(f"  C (константа): {C:.4f}")

# --- 4. Розрахунок статистики Chi-squared ---
# Формула з книги: Chi^2 = (2.303/C) * [ (n-k)*lg(S_B^2) - sum((n_j-1)*lg(S_j^2)) ]
# 2.303 * lg(x) - це те саме, що ln(x) (натуральний логарифм).
# Більш стандартна формула (яку використовує scipy) виглядає так:
# Chi^2 = (1/C) * [ (n-k)*ln(S_B^2) - sum((n_j-1)*ln(S_j^2)) ]
# Ми будемо використовувати стандартну формулу з натуральним логарифмом (np.log)

term_A = n_minus_k * np.log(S_B_sq)
term_B = (df1 * np.log(s1_sq)) + (df2 * np.log(s2_sq))
chi_sq_stat_manual = (term_A - term_B) / C

# Ступені свободи для критерію Бартлетта = k - 1
df_bartlett = k - 1
p_value_manual = stats.chi2.sf(chi_sq_stat_manual, df_bartlett)

print(f"\n  Статистика Бартлетта Chi-sq (розрахована вручну): {chi_sq_stat_manual:.4f}")
print(f"  Ступені свободи (k-1): {df_bartlett}")
print(f"  p-value (розраховане вручну): {p_value_manual:.4f}")

# --- 5. Перевірка за допомогою вбудованої функції ---
scipy_stat, scipy_p = stats.bartlett(sample1, sample2)
print("\n--- Перевірка за допомогою 'scipy.stats.bartlett' ---")
print(f"  scipy Статистика = {scipy_stat:.4f}")
print(f"  scipy p-value = {scipy_p:.4f}")

# --- 6. Висновок ---
print("\n--- Висновок ---")
if p_value_manual > alpha:
    print(f"  p-value ({p_value_manual:.4f}) > alpha ({alpha}). Немає підстав відхилити H0. Дисперсії однорідні.\n")
else:
    print(f"  p-value ({p_value_manual:.4f}) <= alpha ({alpha}). Відхиляємо H0. Дисперсії неоднорідні.\n")

--- 1. F-критерій (як у секції 6.1) ---
  Дисперсія S1^2 = 11.1321 (df1 = 9)
  Дисперсія S2^2 = 9.6787 (df2 = 10)
  F-статистика = 1.1502
  p-value = 0.8247
  Висновок: p-value > alpha. Немає підстав відхилити H0. Дисперсії однорідні.


--- 2. Критерій Бартлетта (детальний розрахунок за секцією 6.2) ---
  k (кількість сукупностей): 2
  n1 (об'єм вибірки 1): 10, n1-1 = 9
  n2 (об'єм вибірки 2): 11, n2-1 = 10
  n (загальний об'єм): 21
  n-k (загальні ступені свободи): 19
  S1^2 (дисперсія 1): 11.1321
  S2^2 (дисперсія 2): 9.6787

  S_B^2 (об'єднана дисперсія): 10.3672
  C (константа): 1.0528

  Статистика Бартлетта Chi-sq (розрахована вручну): 0.0441
  Ступені свободи (k-1): 1
  p-value (розраховане вручну): 0.8337

--- Перевірка за допомогою 'scipy.stats.bartlett' ---
  scipy Статистика = 0.0441
  scipy p-value = 0.8337

--- Висновок ---
  p-value (0.8337) > alpha (0.05). Немає підстав відхилити H0. Дисперсії однорідні.



<h1>ПАРАГРАФ 7.3<h1>

In [7]:
np.set_printoptions(precision=4, suppress=True)

In [8]:
# --- Вхідні параметри ---
i = 4
j = 1
alpha = 0.1 # Рівень значущості з завдання 7.3

# --- Перша бригада (n1 = 8) ---
# x11 (Вміст міді), x12 (Вміст марганцю)
copper1 = np.array([
    8 + j,
    11,
    12,
    10,
    9 + j,
    14,
    6 + 2*j,
    12
])

manganese1 = np.array([
    206,
    210,
    212,
    216,
    201,
    201,
    165 + i/2,
    195
])

# Створюємо матрицю X1 (n1 x 2)
X1 = np.stack((copper1, manganese1), axis=1)
n1 = len(X1)

# --- Друга бригада (n2 = 12) ---
# x21 (Вміст міді), x22 (Вміст марганцю)
copper2 = np.array([
    15,
    16,
    14,
    18,
    22,
    12 + j,
    17,
    14 + 3*j,
    20,
    24,
    10 + 2*j,
    18
])

manganese2 = np.array([
    215,
    212 + i,
    214,
    225,
    230,
    207,
    256,
    236,
    302,
    220,
    214,
    198 + i
])

# Створюємо матрицю X2 (n2 x 2)
X2 = np.stack((copper2, manganese2), axis=1)
n2 = len(X2)

print(f"--- Вхідні дані (i={i}, j={j}) ---")
print(f"Перша бригада (n1 = {n1}):\n{X1}\n")
print(f"Друга бригада (n2 = {n2}):\n{X2}\n")

--- Вхідні дані (i=4, j=1) ---
Перша бригада (n1 = 8):
[[  9. 206.]
 [ 11. 210.]
 [ 12. 212.]
 [ 10. 216.]
 [ 10. 201.]
 [ 14. 201.]
 [  8. 167.]
 [ 12. 195.]]

Друга бригада (n2 = 12):
[[ 15 215]
 [ 16 216]
 [ 14 214]
 [ 18 225]
 [ 22 230]
 [ 13 207]
 [ 17 256]
 [ 17 236]
 [ 20 302]
 [ 24 220]
 [ 12 214]
 [ 18 202]]



In [9]:
# Кількість змінних (p, у книзі позначено як 'm')
p = X1.shape[1]

# 1. Вектори середніх
mean1 = np.mean(X1, axis=0)
mean2 = np.mean(X2, axis=0)

# 2. Матриці коваріацій (з ddof=1 для незміщеної оцінки)
# C1 та C2 - це S_1 та S_2 з прикладів, але НЕ S з формули 7.1
cov1 = np.cov(X1, rowvar=False, ddof=1)
cov2 = np.cov(X2, rowvar=False, ddof=1)

print(f"Кількість змінних (p): {p}")
print(f"Вектор середніх x_bar_1 (мідь, марганець): {mean1}")
print(f"Вектор середніх x_bar_2 (мідь, марганець): {mean2}\n")

print(f"Матриця коваріацій C1 (n1-1 = {n1-1}):\n{cov1}\n")
print(f"Матриця коваріацій C2 (n2-1 = {n2-1}):\n{cov2}\n")

Кількість змінних (p): 2
Вектор середніх x_bar_1 (мідь, марганець): [ 10.75 201.  ]
Вектор середніх x_bar_2 (мідь, марганець): [ 17.1667 228.0833]

Матриця коваріацій C1 (n1-1 = 7):
[[  3.6429  11.7143]
 [ 11.7143 234.8571]]

Матриця коваріацій C2 (n2-1 = 11):
[[ 12.697   34.6212]
 [ 34.6212 747.5379]]



In [10]:
# 1. Розраховуємо матриці сум квадратів та добутків (SSCP)
# (k_1^T * k_1) та (k_2^T * k_2) з формули
sscp1 = cov1 * (n1 - 1)
sscp2 = cov2 * (n2 - 1)

# 2. Розраховуємо об'єднану коваріаційну матрицю S
df_pooled = n1 + n2 - 2
S_pooled = (sscp1 + sscp2) / df_pooled

# 3. Розраховуємо обернену матрицю S^(-1)
S_inv = np.linalg.inv(S_pooled)

print(f"Матриця SSCP 1 (k1^T * k1):\n{sscp1}\n")
print(f"Матриця SSCP 2 (k2^T * k2):\n{sscp2}\n")
print(f"Об'єднана коваріаційна матриця S (df = {df_pooled}):\n{S_pooled}\n")
print(f"Обернена матриця S^(-1):\n{S_inv}\n")

Матриця SSCP 1 (k1^T * k1):
[[  25.5   82. ]
 [  82.  1644. ]]

Матриця SSCP 2 (k2^T * k2):
[[ 139.6667  380.8333]
 [ 380.8333 8222.9167]]

Об'єднана коваріаційна матриця S (df = 18):
[[  9.1759  25.713 ]
 [ 25.713  548.162 ]]

Обернена матриця S^(-1):
[[ 0.1255 -0.0059]
 [-0.0059  0.0021]]



In [11]:
# 1. Вектор різниці середніх (d = x_bar_1 - x_bar_2)
d = mean1 - mean2

# 2. Обчислення T^2
# T^2 = (n1*n2 / (n1+n2)) * d^T * S^(-1) * d
coeff = (n1 * n2) / (n1 + n2)
T2_stat = coeff * (d.T @ S_inv @ d)

print(f"Вектор різниці середніх d: {d}")
print(f"Коефіцієнт (n1*n2 / (n1+n2)): {coeff:.4f}")
print(f"\nРозрахована статистика T-квадрат Готеллінга: T^2 = {T2_stat:.4f}")

Вектор різниці середніх d: [ -6.4167 -27.0833]
Коефіцієнт (n1*n2 / (n1+n2)): 4.8000

Розрахована статистика T-квадрат Готеллінга: T^2 = 22.3736


In [15]:
from scipy.stats import f

# 1. Розрахунок критичного значення F
df1 = p
df2 = n1 + n2 - p - 1
F_crit = f.ppf(1 - alpha, df1, df2)

# 2. Розрахунок критичного T^2
T2_crit_coeff = ((n1 + n2 - 2) * p) / (n1 + n2 - p - 1)
T2_crit = T2_crit_coeff * F_crit

print(f"--- Загальний висновок (Тест Готеллінга) ---")
print(f"Рівень значущості alpha: {alpha}")
print(f"Ступені свободи F-критерію: df1 = {df1}, df2 = {df2}")
print(f"Критичне значення F({df1}, {df2}) = {F_crit:.4f}")
print(f"Критичне значення T^2_alpha = {T2_crit:.4f}\n")

# 3. Висновок
print(f"Результат: T^2 = {T2_stat:.4f}, T^2_alpha = {T2_crit:.4f}")
if T2_stat > T2_crit:
    print(f"Висновок: T^2 > T^2_alpha. Гіпотеза H0 відхиляється.")
    print("Існує статистично значуща різниця між векторами середніх (мідь та марганець) для двох бригад.")
else:
    print(f"Висновок: T^2 <= T^2_alpha. Гіпотеза H0 не відхиляється.")
    print("Немає статистично значущої різниці між векторами середніх для двох бригад.")

--- Загальний висновок (Тест Готеллінга) ---
Рівень значущості alpha: 0.1
Ступені свободи F-критерію: df1 = 2, df2 = 17
Критичне значення F(2, 17) = 2.6446
Критичне значення T^2_alpha = 5.6004

Результат: T^2 = 22.3736, T^2_alpha = 5.6004
Висновок: T^2 > T^2_alpha. Гіпотеза H0 відхиляється.
Існує статистично значуща різниця між векторами середніх (мідь та марганець) для двох бригад.


In [16]:
print(f"\n--- Часткові критерії T^2_cj (Оцінка внеску змінних) ---")

# Критичне значення для часткових тестів
df1_part = 1
df2_part = n1 + n2 - 2 # df для S_pooled
F_crit_part = f.ppf(1 - alpha, df1_part, df2_part)

print(f"Критичне значення F_alpha({df1_part}, {df2_part}) = {F_crit_part:.4f}\n")

# --- Змінна 1: Мідь (j=1) ---
d_j1 = d[0] # Різниця середніх для міді
S_jj1 = S_pooled[0, 0] # Діагональний елемент S для міді

T2_c1 = (coeff * (d_j1**2)) / S_jj1

print(f"Мідь (j=1):")
print(f"  T^2_c1 = {T2_c1:.4f}")
if T2_c1 > F_crit_part:
    print(f"  Висновок: T^2_c1 > F_crit. Вміст міді значуще відрізняється.\n")
else:
    print(f"  Висновок: T^2_c1 <= F_crit. Вміст міді значуще не відрізняється.\n")

# --- Змінна 2: Марганець (j=2) ---
d_j2 = d[1] # Різниця середніх для марганцю
S_jj2 = S_pooled[1, 1] # Діагональний елемент S для марганцю

T2_c2 = (coeff * (d_j2**2)) / S_jj2

print(f"Марганець (j=2):")
print(f"  T^2_c2 = {T2_c2:.4f}")
if T2_c2 > F_crit_part:
    print(f"  Висновок: T^2_c2 > F_crit. Вміст марганцю значуще відрізняється.\n")
else:
    print(f"  Висновок: T^2_c2 <= F_crit. Вміст марганцю значуще не відрізняється.\n")


--- Часткові критерії T^2_cj (Оцінка внеску змінних) ---
Критичне значення F_alpha(1, 18) = 3.0070

Мідь (j=1):
  T^2_c1 = 21.5382
  Висновок: T^2_c1 > F_crit. Вміст міді значуще відрізняється.

Марганець (j=2):
  T^2_c2 = 6.4230
  Висновок: T^2_c2 > F_crit. Вміст марганцю значуще відрізняється.



<h1>ПАРАГРАФ 7.6<h1>

In [17]:
# --- Вхідні параметри ---
i = 4
alpha = 0.05 # Рівень значущості (стандартний, як у Прикладі 16)

# Вектор нормативів (заданий постійний вектор)
# 14% хрому, 8% титану
mu_0 = np.array([14, 8])

# --- Дані вибірки (n = 12) ---

# Вміст хрому (x1)
x1_chromium = np.array([
    21,
    19 + i,
    13,
    18,
    24,
    15,
    17 + i,
    23,
    14,
    25 + i,
    19,
    22
])

# Вміст титану (x2)
x2_titanium = np.array([
    7,
    9,
    8 + i,
    10,
    13,
    11,
    12 + i,
    8,
    9,
    7,
    10 + i,
    10
])

# Створюємо матрицю X (n x p)
X = np.stack((x1_chromium, x2_titanium), axis=1)

n = X.shape[0] # Кількість спостережень (n = 12)
p = X.shape[1] # Кількість змінних (p = 2)

print(f"--- Вхідні дані (i={i}) ---")
print(f"Норматив (вектор mu_0): {mu_0}")
print(f"Кількість спостережень (n): {n}")
print(f"Кількість змінних (p): {p}")
print(f"\nМатриця спостережень X (n={n}, p={p}):\n{X}")

--- Вхідні дані (i=4) ---
Норматив (вектор mu_0): [14  8]
Кількість спостережень (n): 12
Кількість змінних (p): 2

Матриця спостережень X (n=12, p=2):
[[21  7]
 [23  9]
 [13 12]
 [18 10]
 [24 13]
 [15 11]
 [21 16]
 [23  8]
 [14  9]
 [29  7]
 [19 14]
 [22 10]]


In [18]:
# 1. Вибірковий вектор середніх (x_bar)
mean_vec = np.mean(X, axis=0)

# 2. Коваріаційна матриця (S)
#    (ddof=1 для незміщеної оцінки, тобто ділення на n-1)
S = np.cov(X, rowvar=False, ddof=1)

# 3. Обернена коваріаційна матриця (S_inv)
S_inv = np.linalg.inv(S)

print(f"Вибірковий вектор середніх (x_bar): {mean_vec}")
print(f"\nКоваріаційна матриця S (n-1 = {n-1}):\n{S}")
print(f"\nОбернена коваріаційна матриця S^(-1):\n{S_inv}")

Вибірковий вектор середніх (x_bar): [20.1667 10.5   ]

Коваріаційна матриця S (n-1 = 11):
[[21.4242 -3.5455]
 [-3.5455  7.9091]]

Обернена коваріаційна матриця S^(-1):
[[0.0504 0.0226]
 [0.0226 0.1366]]


In [19]:
# 1. Вектор різниці середніх (d = x_bar - mu_0)
d = mean_vec - mu_0

# 2. Обчислення T^2
# T^2 = n * d^T * S^(-1) * d
T2_stat = n * (d.T @ S_inv @ d)

print(f"Вектор різниці середніх d = (x_bar - mu_0): {d}")
print(f"\nРозрахована статистика T-квадрат Готеллінга: T^2 = {T2_stat:.4f}")

Вектор різниці середніх d = (x_bar - mu_0): [6.1667 2.5   ]

Розрахована статистика T-квадрат Готеллінга: T^2 = 41.6113


In [20]:
# 1. Розрахунок критичного значення F
df1 = p
df2 = n - p
F_crit = f.ppf(1 - alpha, df1, df2)

# 2. Розрахунок критичного T^2
# Формула: T^2_alpha = ((n-1)*p) / (n-p) * F_alpha
T2_crit_coeff = ((n - 1) * p) / (n - p)
T2_crit = T2_crit_coeff * F_crit

print(f"--- Загальний висновок (Тест Готеллінга) ---")
print(f"Рівень значущості alpha: {alpha}")
print(f"Ступені свободи F-критерію: df1 = {df1}, df2 = {df2}")
print(f"Критичне значення F({df1}, {df2}) = {F_crit:.4f}")
print(f"Критичне значення T^2_alpha = {T2_crit_coeff:.2f} * {F_crit:.4f} = {T2_crit:.4f}\n")

# 3. Висновок
print(f"Результат: T^2 = {T2_stat:.4f}, T^2_alpha = {T2_crit:.4f}")
if T2_stat > T2_crit:
    print(f"Висновок: T^2 > T^2_alpha. Гіпотеза H0 (про дотримання нормативів) відхиляється.")
    print("Існує статистично значуща різниця між показниками заготовок та заданими нормативами.")
else:
    print(f"Висновок: T^2 <= T^2_alpha. Гіпотеза H0 (про дотримання нормативів) не відхиляється.")
    print("Немає статистично значущих доказів того, що нормативи не дотримуються.")

--- Загальний висновок (Тест Готеллінга) ---
Рівень значущості alpha: 0.05
Ступені свободи F-критерію: df1 = 2, df2 = 10
Критичне значення F(2, 10) = 4.1028
Критичне значення T^2_alpha = 2.20 * 4.1028 = 9.0262

Результат: T^2 = 41.6113, T^2_alpha = 9.0262
Висновок: T^2 > T^2_alpha. Гіпотеза H0 (про дотримання нормативів) відхиляється.
Існує статистично значуща різниця між показниками заготовок та заданими нормативами.


In [26]:
print(f"\n--- Часткові критерії T^2_dj (Оцінка внеску змінних)---")

# Критичне значення для часткових тестів (p=1)
df1_part = 1
df2_part = n - 1
F_crit_part = f.ppf(1 - alpha, df1_part, df2_part)

print(f"Критичне значення F_alpha({df1_part}, {df2_part}) = {F_crit_part:.4f}\n")

# --- Змінна 1: Хром (j=1) ---
d_j1 = d[0]            # Різниця середніх для хрому
S_jj1 = S[0, 0]        # Діагональний елемент S (дисперсія) для хрому

T2_d1 = (n * (d_j1**2)) / S_jj1

print(f"Хром (j=1):")
print(f"  T^2_d1 = {T2_d1:.4f}")
if T2_d1 > F_crit_part:
    print(f"  Висновок: T^2_d1 > F_crit. Вміст хрому значуще відрізняється від нормативу (14%).\n")
else:
    print(f"  Висновок: T^2_d1 <= F_crit. Вміст хрому значуще не відрізняється від нормативу.\n")

# --- Змінна 2: Титан (j=2) ---
d_j2 = d[1]            # Різниця середніх для титану
S_jj2 = S[1, 1]        # Діагональний елемент S (дисперсія) для титану

T2_d2 = (n * (d_j2**2)) / S_jj2

print(f"Титан (j=2):")
print(f"  T^2_d2 = {T2_d2:.4f}")
if T2_d2 > F_crit_part:
    print(f"  Висновок: T^2_d2 > F_crit. Вміст титану значуще відрізняється від нормативу (8%).\n")
else:
    print(f"  Висновок: T^2_d2 <= F_crit. Вміст титану значуще не відрізняється від нормативу.\n")


--- Часткові критерії T^2_dj (Оцінка внеску змінних)---
Критичне значення F_alpha(1, 11) = 4.8443

Хром (j=1):
  T^2_d1 = 21.2999
  Висновок: T^2_d1 > F_crit. Вміст хрому значуще відрізняється від нормативу (14%).

Титан (j=2):
  T^2_d2 = 9.4828
  Висновок: T^2_d2 > F_crit. Вміст титану значуще відрізняється від нормативу (8%).



<h1>ПАРАГРАФ 7.9<h1>

In [27]:
from scipy.stats import chi2

In [28]:
# --- Вхідні параметри ---
i = 4
j = 1
# Рівень значущості (як у Прикладі 17)
alpha = 0.05

# --- Перша бригада (n1 = 8) ---
copper1 = np.array([
    8 + j,
    11,
    12,
    10,
    9 + j,
    14,
    6 + 2*j,
    12
])
manganese1 = np.array([
    206,
    210,
    212,
    216,
    201,
    201,
    165 + i/2,
    195
])
X1 = np.stack((copper1, manganese1), axis=1)

# --- Друга бригада (n2 = 12) ---
copper2 = np.array([
    15,
    16,
    14,
    18,
    22,
    12 + j,
    17,
    14 + 3*j,
    20,
    24,
    10 + 2*j,
    18
])
manganese2 = np.array([
    215,
    212 + i,
    214,
    225,
    230,
    207,
    256,
    236,
    302,
    220,
    214,
    198 + i
])
X2 = np.stack((copper2, manganese2), axis=1)

print("--- 1. Початкові параметри (розділ 7.7) ---")
# m - кількість ознак (змінних)
m = X1.shape[1]
n1 = len(X1)
n2 = len(X2)

# Ступені свободи
df1 = n1 - 1
df2 = n2 - 1
df_pooled = df1 + df2 # (n1 + n2 - 2)

print(f"  Кількість змінних (m): {m}")
print(f"  Об'єм вибірки 1 (n1): {n1}, ступені свободи (n1-1): {df1}")
print(f"  Об'єм вибірки 2 (n2): {n2}, ступені свободи (n2-1): {df2}")
print(f"  Загальні ступені свободи (n1+n2-2): {df_pooled}")

--- 1. Початкові параметри (розділ 7.7) ---
  Кількість змінних (m): 2
  Об'єм вибірки 1 (n1): 8, ступені свободи (n1-1): 7
  Об'єм вибірки 2 (n2): 12, ступені свободи (n2-1): 11
  Загальні ступені свободи (n1+n2-2): 18


In [29]:
print("\n--- 2. Матриці коваріацій та їх детермінанти ---")

# 1. Матриці S1, S2 та їх детермінанти
S1 = np.cov(X1, rowvar=False, ddof=1)
det_S1 = np.linalg.det(S1)

S2 = np.cov(X2, rowvar=False, ddof=1)
det_S2 = np.linalg.det(S2)

print(f"  Матриця S1:\n{S1}")
print(f"  Детермінант |S1| = {det_S1:.4f}\n")

print(f"  Матриця S2:\n{S2}")
print(f"  Детермінант |S2| = {det_S2:.4f}\n")

# 2. Об'єднана коваріаційна матриця S_p
# S_p = (1 / (n1+n2-2)) * [ (n1-1)*S1 + (n2-1)*S2 ]
S_pooled = ( (S1 * df1) + (S2 * df2) ) / df_pooled
det_Sp = np.linalg.det(S_pooled)

print(f"  Об'єднана матриця S_p:\n{S_pooled}")
print(f"  Детермінант |S_p| = {det_Sp:.4f}")


--- 2. Матриці коваріацій та їх детермінанти ---
  Матриця S1:
[[  3.6429  11.7143]
 [ 11.7143 234.8571]]
  Детермінант |S1| = 718.3265

  Матриця S2:
[[ 12.697   34.6212]
 [ 34.6212 747.5379]]
  Детермінант |S2| = 8292.8375

  Об'єднана матриця S_p:
[[  9.1759  25.713 ]
 [ 25.713  548.162 ]]
  Детермінант |S_p| = 4368.7378


In [30]:
print("\n--- 3. Розрахунок статистики тесту ---")

# 1. Обчислюємо -2 ln(v1)
# -2 ln(v1) = (n1+n2-2) * ln|S_p| - [ (n1-1)*ln|S1| + (n2-1)*ln|S2| ]
term1 = df_pooled * np.log(det_Sp)
term2 = (df1 * np.log(det_S1)) + (df2 * np.log(det_S2))
minus_2_ln_v1 = term1 - term2

print(f"  -2 ln(v1) = {minus_2_ln_v1:.4f}")

# 2. Обчислюємо коефіцієнт b
m_term = (2 * m**2 + 3 * m - 1) / (6 * (m + 1))
df_term = (1/df1) + (1/df2) - (1/df_pooled)
b = 1 - (df_term * m_term)

print(f"  Коефіцієнт b = {b:.4f}")

# 3. Обчислюємо w_CT (статистика тесту)
# w_CT = b * (-2 ln v1)
w_ct = b * minus_2_ln_v1

print(f"  Статистика w_CT = b * (-2 ln v1) = {w_ct:.4f}")


--- 3. Розрахунок статистики тесту ---
  -2 ln(v1) = 5.5870
  Коефіцієнт b = 0.8713
  Статистика w_CT = b * (-2 ln v1) = 4.8679


In [31]:
print("\n--- 4. Критичне значення та висновок ---")

# 1. Ступені свободи для Chi-square
# nu = m*(m+1) / 2
nu = (m * (m + 1)) / 2

# 2. Критичне значення w_KP
w_kp = chi2.ppf(1 - alpha, nu)

print(f"  Рівень значущості alpha = {alpha}")
print(f"  Ступені свободи nu = m(m+1)/2 = {nu}")
print(f"  Критичне значення w_KP = Chi-sq_alpha(nu) = {w_kp:.4f}")

# 3. Висновок
print(f"\n  Результат: w_CT = {w_ct:.4f}, w_KP = {w_kp:.4f}")
if w_ct > w_kp:
    print(f"  Висновок: w_CT > w_KP. Гіпотеза H0 (про рівність коваріаційних матриць) ВІДХИЛЯЄТЬСЯ.")
else:
    print(f"  Висновок: w_CT <= w_KP. Гіпотеза H0 (про рівність коваріаційних матриць) НЕ ВІДХІЛЯЄТЬСЯ.")


--- 4. Критичне значення та висновок ---
  Рівень значущості alpha = 0.05
  Ступені свободи nu = m(m+1)/2 = 3.0
  Критичне значення w_KP = Chi-sq_alpha(nu) = 7.8147

  Результат: w_CT = 4.8679, w_KP = 7.8147
  Висновок: w_CT <= w_KP. Гіпотеза H0 (про рівність коваріаційних матриць) НЕ ВІДХІЛЯЄТЬСЯ.


<h1>ПАРАГРАФ 8.3<h1>

In [33]:
import pandas as pd

In [34]:
# --- Вхідні параметри ---
i = 4
# Візьмемо рівень значущості 0.1, як у Прикладі 18
alpha = 0.1

# --- Розрахунок значень вибірки ---
# [i/2] = [4/2] = [2] = 2
# [9 + i/2] = [9 + 2] = [11] = 11
# [11 + i/2] = [11 + 2] = [13] = 13

x = np.array([
    3 + i,      # 7
    8 + i,      # 12
    14 + (i//2), # 16 (використовуємо i//2 для цілої частини)
    8 + i,      # 12
    10 + i,     # 14
    9 + (i//2),  # 11
    6 + i,      # 10
    4 + i,      # 8
    7 + i,      # 11
    10 + i,     # 14
    8 + i,      # 12
    11 + (i//2)  # 13
])

n = len(x)

print(f"--- Вхідні дані (i={i}) ---")
print(f"Вибірка (x): {x}")
print(f"Розмір вибірки (n): {n}")
print(f"Рівень значущості (alpha): {alpha}")

--- Вхідні дані (i=4) ---
Вибірка (x): [ 7 12 16 12 14 11 10  8 11 14 12 13]
Розмір вибірки (n): 12
Рівень значущості (alpha): 0.1


In [35]:
print("--- Кроки 1-3: Розрахунок рангів ---")

# Крок 1: Обчислюємо центр mu (середнє)
mu = np.mean(x)
print(f"Центр розподілу (середнє mu): {mu:.4f}")

# Обчислюємо різниці
diff = x - mu

# Крок 2: Створюємо вибірку z_i = |x_i - mu|
# (На відміну від стандартного тесту Вілкоксона, згідно Прикладу 18,
# ми не відкидаємо нульові різниці, якщо вони є)
z = np.abs(diff)

# Крок 3: Розраховуємо ранги R_i для z_i
# 'average' - стандартний метод обробки однакових значень
ranks = stats.rankdata(z, method='average')

# Створимо DataFrame для наочності
df = pd.DataFrame({
    'x_i': x,
    'x_i - mu': diff,
    'z_i = |x_i - mu|': z,
    'R_i (Ранг)': ranks
})
print(df.to_string())

--- Кроки 1-3: Розрахунок рангів ---
Центр розподілу (середнє mu): 11.6667
    x_i  x_i - mu  z_i = |x_i - mu|  R_i (Ранг)
0     7 -4.666667          4.666667        12.0
1    12  0.333333          0.333333         2.0
2    16  4.333333          4.333333        11.0
3    12  0.333333          0.333333         2.0
4    14  2.333333          2.333333         8.5
5    11 -0.666667          0.666667         4.5
6    10 -1.666667          1.666667         7.0
7     8 -3.666667          3.666667        10.0
8    11 -0.666667          0.666667         4.5
9    14  2.333333          2.333333         8.5
10   12  0.333333          0.333333         2.0
11   13  1.333333          1.333333         6.0


In [36]:
print("\n--- Кроки 4-7: Розрахунок статистики та висновок ---")

# Крок 4: Розраховуємо K (сума рангів, де x_i - mu > 0)
positive_diff_mask = (diff > 0)
ranks_for_K = ranks[positive_diff_mask]
K = np.sum(ranks_for_K)

print(f"Ранги для K (де x_i - mu > 0): {ranks_for_K}")
print(f"Статистика K (сума рангів): {K:.2f}")

# Крок 5: Розраховуємо EK (математичне сподівання) та DK (дисперсію)
EK = (1/4) * n * (n + 1)
DK_var = (1/24) * n * (n + 1) * (2*n + 1)
DK_std = np.sqrt(DK_var) # Стандартне відхилення

print(f"\nEK = (1/4)*n*(n+1) = {EK:.2f}")
print(f"DK (дисперсія) = (1/24)*n*(n+1)*(2n+1) = {DK_var:.2f}")
print(f"sqrt(DK) (станд. відхилення) = {DK_std:.2f}")

# Крок 6: Розраховуємо фінальну статистику A
A = (K - EK) / DK_std
print(f"\nСтатистика A = (K - EK) / sqrt(DK) = {A:.4f}")

# Крок 7: Гіпотеза та висновок
# H0 (нульова гіпотеза): Розподіл симетричний.
# Ha (альтернативна): Розподіл несиметричний.

# Знаходимо критичні значення u для alpha (двосторонній тест)
# u_lower = u_(alpha/2), u_upper = u_(1 - alpha/2)
u_lower = stats.norm.ppf(alpha / 2)
u_upper = stats.norm.ppf(1 - alpha / 2)

print(f"\nКритична область (alpha = {alpha}): A < {u_lower:.4f} або A > {u_upper:.4f}")

# Приймаємо рішення
if (A < u_lower) or (A > u_upper):
    print(f"Висновок: A ({A:.4f}) потрапляє у критичну область.")
    print("Гіпотеза H0 про симетричність розподілу ВІДХИЛЯЄТЬСЯ.")
else:
    print(f"Висновок: A ({A:.4f}) знаходиться в межах ({u_lower:.4f}, {u_upper:.4f}).")
    print("Гіпотеза H0 про симетричність розподілу ПРИЙМАЄТЬСЯ.")


--- Кроки 4-7: Розрахунок статистики та висновок ---
Ранги для K (де x_i - mu > 0): [ 2.  11.   2.   8.5  8.5  2.   6. ]
Статистика K (сума рангів): 40.00

EK = (1/4)*n*(n+1) = 39.00
DK (дисперсія) = (1/24)*n*(n+1)*(2n+1) = 162.50
sqrt(DK) (станд. відхилення) = 12.75

Статистика A = (K - EK) / sqrt(DK) = 0.0784

Критична область (alpha = 0.1): A < -1.6449 або A > 1.6449
Висновок: A (0.0784) знаходиться в межах (-1.6449, 1.6449).
Гіпотеза H0 про симетричність розподілу ПРИЙМАЄТЬСЯ.
